"""Prometheus alerting rules — production-ready alert definitions.

Defines alert rules that can be loaded into Prometheus Alertmanager.
Rules cover latency, error rates, retrieval quality, and system health.

Rule file: deploy/prometheus/alerts.yml

Reference:
    TECHNICAL_DEEP_DIVE.md §40.4 — "Prometheus 指标化"
    Expected impact: p95_latency、error_rate 实时可见, 支持告警
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Alert rule definitions
# ---------------------------------------------------------------------------

ALERT_RULES_YAML = """# Enterprise Agentic RAG — Prometheus Alerting Rules
# Generated by observability/prometheus_alerts.py
#
# Load with:
#   promtool check rules deploy/prometheus/alerts.yml
#   curl -X POST http://localhost:9090/-/reload

groups:
  - name: enterprise_rag_latency
    rules:
      # ── P95 latency alerts ──
      - alert: HighP95Latency
        expr: histogram_quantile(0.95, rate(rag_request_latency_seconds_bucket[5m])) > 10
        for: 5m
        labels:
          severity: warning
          component: rag_pipeline
        annotations:
          summary: "RAG pipeline P95 latency exceeds 10 seconds"
          description: "P95 latency is {{ $value | humanize }}s over the last 5 minutes. Check retrieval backend and LLM provider health."

      - alert: CriticalP95Latency
        expr: histogram_quantile(0.95, rate(rag_request_latency_seconds_bucket[5m])) > 30
        for: 3m
        labels:
          severity: critical
          component: rag_pipeline
        annotations:
          summary: "RAG pipeline P95 latency critically high ({{ $value }}s)"
          description: "Immediate investigation required. Check downstream service availability."

  - name: enterprise_rag_errors
    rules:
      # ── Error rate alerts ──
      - alert: HighErrorRate
        expr: rate(rag_request_errors_total[5m]) / rate(rag_requests_total[5m]) > 0.10
        for: 5m
        labels:
          severity: warning
          component: rag_pipeline
        annotations:
          summary: "RAG error rate exceeds 10%"
          description: "Error rate is {{ $value | humanizePercentage }}. Check logs for failure patterns."

      - alert: CriticalErrorRate
        expr: rate(rag_request_errors_total[5m]) / rate(rag_requests_total[5m]) > 0.25
        for: 3m
        labels:
          severity: critical
          component: rag_pipeline
        annotations:
          summary: "RAG error rate critically high ({{ $value | humanizePercentage }})"
          description: "More than 25% of requests are failing. Consider rollback or emergency fix."

      # ── Tool failure rate ──
      - alert: HighToolFailureRate
        expr: rate(rag_tool_errors_total[5m]) / rate(rag_tool_calls_total[5m]) > 0.15
        for: 5m
        labels:
          severity: warning
          component: tool_executor
        annotations:
          summary: "Tool execution failure rate exceeds 15%"
          description: "{{ $value | humanizePercentage }} of tool calls are failing. Check external service integrations."

  - name: enterprise_rag_retrieval
    rules:
      # ── Retrieval quality alerts ──
      - alert: LowRetrievalQuality
        expr: avg(rag_retrieval_top_score) < 0.05
        for: 10m
        labels:
          severity: warning
          component: retrieval
        annotations:
          summary: "Retrieval quality is low (avg top score < 0.05)"
          description: "Documents retrieved have very low relevance. Check index health and embedding quality."

      - alert: HighNoDocRate
        expr: rate(rag_no_doc_retrievals_total[10m]) / rate(rag_retrievals_total[10m]) > 0.20
        for: 10m
        labels:
          severity: warning
          component: retrieval
        annotations:
          summary: "Retrieval returning no documents for >20% of queries"
          description: "{{ $value | humanizePercentage }} of retrievals return no documents. Check ingestion pipeline."

      # ── Fallback rate alerts ──
      - alert: HighFallbackRate
        expr: rate(rag_fallback_total[10m]) / rate(rag_requests_total[10m]) > 0.25
        for: 10m
        labels:
          severity: warning
          component: recovery
        annotations:
          summary: "Fallback rate exceeds 25%"
          description: "{{ $value | humanizePercentage }} of requests are triggering fallback. Check primary retrieval path."

  - name: enterprise_rag_verification
    rules:
      # ── Verification alerts ──
      - alert: LowVerificationPassRate
        expr: rate(rag_verification_pass_total[10m]) / rate(rag_verification_total[10m]) < 0.85
        for: 10m
        labels:
          severity: warning
          component: verifier
        annotations:
          summary: "Answer verification pass rate below 85%"
          description: "Only {{ $value | humanizePercentage }} of answers pass verification. Check retrieval quality and LLM grounding."

      - alert: HighHallucinationRate
        expr: rag_hallucination_rate > 0.15
        for: 10m
        labels:
          severity: critical
          component: verifier
        annotations:
          summary: "Hallucination rate exceeds 15%"
          description: "{{ $value | humanizePercentage }} of claims are flagged as hallucinated. Immediate investigation required."

  - name: enterprise_rag_system
    rules:
      # ── System health alerts ──
      - alert: ServiceDown
        expr: up{job="enterprise_rag"} == 0
        for: 1m
        labels:
          severity: critical
          component: infrastructure
        annotations:
          summary: "Enterprise RAG service is down"
          description: "The /health endpoint is not responding. Check pod/container status."

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes{job="enterprise_rag"} / 1024 / 1024 / 1024 > 20
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Memory usage exceeds 20 GB"
          description: "Process memory is {{ $value }} GB. Check for memory leaks."

      - alert: CacheHitRateDrop
        expr: rate(rag_cache_hits_total[10m]) / rate(rag_cache_requests_total[10m]) < 0.3
        for: 10m
        labels:
          severity: info
          component: cache
        annotations:
          summary: "Semantic cache hit rate below 30%"
          description: "Cache hit rate is {{ $value | humanizePercentage }}. Consider adjusting similarity threshold."
"""


# ---------------------------------------------------------------------------
# Alert rule manager
# ---------------------------------------------------------------------------


@dataclass
class AlertThresholds:
    """Configurable alert thresholds for auto-calibration."""

    p95_latency_warning_s: float = 10.0
    p95_latency_critical_s: float = 30.0
    error_rate_warning: float = 0.10
    error_rate_critical: float = 0.25
    tool_failure_rate_warning: float = 0.15
    retrieval_top_score_min: float = 0.05
    no_doc_rate_warning: float = 0.20
    fallback_rate_warning: float = 0.25
    verification_pass_rate_min: float = 0.85
    hallucination_rate_max: float = 0.15
    memory_usage_gb_warning: float = 20.0
    cache_hit_rate_min: float = 0.30

    def to_dict(self) -> dict[str, Any]:
        return {
            "latency": {
                "p95_warning_s": self.p95_latency_warning_s,
                "p95_critical_s": self.p95_latency_critical_s,
            },
            "errors": {
                "rate_warning": self.error_rate_warning,
                "rate_critical": self.error_rate_critical,
                "tool_failure_warning": self.tool_failure_rate_warning,
            },
            "retrieval": {
                "top_score_min": self.retrieval_top_score_min,
                "no_doc_rate_warning": self.no_doc_rate_warning,
                "fallback_rate_warning": self.fallback_rate_warning,
            },
            "verification": {
                "pass_rate_min": self.verification_pass_rate_min,
                "hallucination_rate_max": self.hallucination_rate_max,
            },
            "system": {
                "memory_gb_warning": self.memory_usage_gb_warning,
                "cache_hit_rate_min": self.cache_hit_rate_min,
            },
        }


def write_alert_rules(path: str = "deploy/prometheus/alerts.yml") -> str:
    """Write the Prometheus alerting rules YAML file.

    Args:
        path: Output file path.

    Returns:
        The file path written.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(ALERT_RULES_YAML)
    logger.info("Prometheus alert rules written to %s", path)
    return path


def get_alert_thresholds() -> AlertThresholds:
    """Get alert thresholds, configurable via environment variables."""
    return AlertThresholds(
        p95_latency_warning_s=float(os.getenv("ALERT_P95_LATENCY_WARNING", "10.0")),
        p95_latency_critical_s=float(os.getenv("ALERT_P95_LATENCY_CRITICAL", "30.0")),
        error_rate_warning=float(os.getenv("ALERT_ERROR_RATE_WARNING", "0.10")),
        error_rate_critical=float(os.getenv("ALERT_ERROR_RATE_CRITICAL", "0.25")),
        tool_failure_rate_warning=float(os.getenv("ALERT_TOOL_FAILURE_WARNING", "0.15")),
        retrieval_top_score_min=float(os.getenv("ALERT_RETRIEVAL_SCORE_MIN", "0.05")),
        no_doc_rate_warning=float(os.getenv("ALERT_NO_DOC_RATE_WARNING", "0.20")),
        fallback_rate_warning=float(os.getenv("ALERT_FALLBACK_RATE_WARNING", "0.25")),
        verification_pass_rate_min=float(os.getenv("ALERT_VERIFY_PASS_MIN", "0.85")),
        hallucination_rate_max=float(os.getenv("ALERT_HALLUCINATION_MAX", "0.15")),
        memory_usage_gb_warning=float(os.getenv("ALERT_MEMORY_GB_WARNING", "20.0")),
        cache_hit_rate_min=float(os.getenv("ALERT_CACHE_HIT_MIN", "0.30")),
    )
